name: "Publish AI Image(latest)"

on:
  workflow_dispatch:
      
jobs:
  build_latest:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_URL: weijinglin/incubator-hugegraph-ai
      BRANCH: main
      IMAGE_URL: linyu2025/rag:latest
      IMAGE_URL_NK: linyu2025/rag-bin:latest
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      OWNER: weijinglin
      REPO: actions
      LAST_AI_HASH: ${{vars.LAST_AI_HASH}}
      
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Checkout latest
      uses: actions/checkout@v4
      with:
        repository: ${{ env.REPOSITORY_URL }}
        ref: ${{ env.BRANCH }}
        fetch-depth: 2

    - name: Get current commit-hash
      run: |
        current_commit_hash=$(git rev-parse HEAD)
        echo "CURRENT_COMMIT_HASH=$current_commit_hash" >> $GITHUB_ENV

    - name: Check if an update is needed
      run: |
        need_update='false'
        if [[ "$CURRENT_COMMIT_HASH" != "$LAST_AI_HASH" ]]; then
          need_update='true'
        fi
        echo "NEED_UPDATE=$need_update" >> $GITHUB_ENV
        # TODO: replace the `if` statements with a graceful exit once GitHub Actions supports it.
        # See https://github.com/actions/runner/issues/662 for more details.

    - name: Build X86 & ARM And Push All
      uses: docker/build-push-action@v5
      if: ${{ env.NEED_UPDATE == 'true' }}
      with:
        context: .
        file: ./docker/Dockerfile.llm
        platforms: linux/amd64,linux/arm64
        tags: ${{ env.IMAGE_URL }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build Binary X86 & ARM And Push All
      uses: docker/build-push-action@v5
      if: ${{ env.NEED_UPDATE == 'true' }}
      with:
        context: .
        file: ./docker/Dockerfile.nk
        # platforms: linux/amd64,linux/arm64
        platforms: linux/amd64
        tags: ${{ env.IMAGE_URL_NK }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Update last commit-hash
      if: ${{ env.NEED_UPDATE == 'true' }}
      run: |
        curl -L -X PATCH \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        -H "Authorization: Bearer $GITHUB_TOKEN" \
        https://api.github.com/repos/$OWNER/$REPO/actions/variables/LAST_AI_HASH \
        -d '{"name":"LAST_AI_HASH","value":"'"$CURRENT_COMMIT_HASH"'"}'
